[build]
builder = "nixpacks"

[deploy]
startCommand = "cd memory-map-backend && npm start"
restartPolicyType = "on_failure"

[[services]]
name = "memory-map-backend"

[services.source]
repo = "Dunni14/wndr"
rootDirectory = "/memory-map-backend"