services:
  - type: web
    name: wndr-backend
    runtime: node
    rootDir: memory-map-backend
    buildCommand: npm install
    startCommand: npx ts-node src/index.ts
    plan: free
    envVars:
      - key: NODE_ENV
        value: production